import {useEffect,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {api} from '../services/api';import {useAuth} from '../hooks/useAuth';import type {Project,ProgressUpdate} from '../types';import {Loading} from '../components/Loading';import {StatusBadge} from '../components/StatusBadge';import {ProjectMap} from '../components/ProjectMap';import {calculateScheduleStatus,expectedProgress} from '../utils/schedule';
function money(n:any){return `₱${Number(n||0).toLocaleString()}`;}
export function ProjectDetail(){
 const{id}=useParams();const{profile}=useAuth();const nav=useNavigate();const[p,setP]=useState<Project|null>(null);const[history,setHistory]=useState<ProgressUpdate[]>([]);const[light,setLight]=useState<any>(null);const[error,setError]=useState('');
 useEffect(()=>{if(id)Promise.all([api.project(id),api.progress(id)]).then(([a,b])=>{setP(a);setHistory(b);}).catch(e=>setError(e.message));},[id]);
 if(!p)return error?<div className="error">{error}</div>:<Loading/>;
 const exp=expectedProgress(p.start_date,p.target_end_date);const sched=calculateScheduleStatus(p.completion_percentage,p.start_date,p.target_end_date);
 return <>
  <div style={{display:'flex',gap:10,alignItems:'center'}}><div><h1 className="page-title">{p.project_name}</h1><p className="muted">{p.project_code} · {p.project_type} · {p.sector}</p></div><div className="right">{profile?.role==='ADMIN'&&<button className="btn primary" onClick={()=>nav(`/admin/projects/${p.id}/edit`)}>Edit Project</button>}</div></div>
  <div className="split"><div className="card"><h3>Project Information</h3><div className="detail-grid">
   <div className="detail-item"><b>Status</b><StatusBadge status={p.status}/></div><div className="detail-item"><b>Current Completion</b>{p.completion_percentage}%<div className="progress-bar"><div className="progress-fill" style={{width:`${p.completion_percentage}%`}}/></div></div>
   <div className="detail-item"><b>Project Type</b>{p.project_type}</div><div className="detail-item"><b>Sector</b>{p.sector}</div><div className="detail-item"><b>Approved Budget</b>{money(p.budget)}</div><div className="detail-item"><b>Contract Amount</b>{money(p.contract_amount)}</div>
   <div className="detail-item"><b>Funding Source</b>{p.funding_source||'—'}</div><div className="detail-item"><b>Contractor</b>{p.contractor||'—'}</div><div className="detail-item"><b>Contract Reference</b>{p.contract_reference||'—'}</div><div className="detail-item"><b>Implementing Agency</b>{p.implementing_agency||'—'}</div>
   <div className="detail-item"><b>Location</b>{p.location_name||'—'}</div><div className="detail-item"><b>Barangay / City / Province</b>{[p.barangay,p.city,p.province].filter(Boolean).join(' / ')||'—'}</div><div className="detail-item"><b>Start Date</b>{p.start_date||'—'}</div><div className="detail-item"><b>Target End</b>{p.target_end_date||'—'}</div><div className="detail-item"><b>Actual Completion</b>{p.actual_completion_date||'—'}</div>
   <div className="detail-item"><b>Schedule Status</b>{sched}<div className="small muted">Expected now: {exp===null?'Insufficient data':`${exp.toFixed(1)}%`}</div></div>
  </div><div className="detail-item" style={{marginTop:10}}><b>Description</b>{p.description||'—'}</div></div><div className="card map-card"><ProjectMap projects={[p]} selectedId={p.id}/></div></div>
  <div className="card" style={{marginTop:16}}><h3>Project Monitoring Evidence</h3><div className="timeline">{history.length===0?<div className="muted">No progress history recorded.</div>:history.map(h=><div className="timeline-item" key={h.id}><b>{h.progress_percentage}%</b> · {new Date(h.progress_date).toLocaleDateString()}<div>{h.remarks||'No remarks'}</div>{h.media.length>0&&<div className="gallery" style={{marginTop:10}}>{h.media.map(m=><div key={m.id} style={{position:'relative'}}><img src={m.public_url} alt={m.caption||m.file_name} onClick={()=>setLight(m)}/>{profile?.role==='ADMIN'&&<button className="btn danger" style={{position:'absolute',right:5,bottom:5,padding:'3px 6px'}} onClick={async()=>{if(confirm('Delete this monitoring photo?')){await api.deleteMedia(m.id);setHistory(await api.progress(p.id));}}}>Delete</button>}<div className="small muted">{m.caption||m.file_name}{m.taken_at?` · Taken ${new Date(m.taken_at).toLocaleDateString()}`:''}</div></div>)}</div>}</div>)}</div><p className="footer-note">Schedule status uses the documented transparent rules: delayed when the target date has passed and the project is incomplete; at risk when actual progress trails expected progress by the configured threshold; otherwise on track. Missing schedule data yields insufficient data.</p></div>
  {light&&<div onClick={()=>setLight(null)} style={{position:'fixed',inset:0,background:'#000b',zIndex:100,display:'grid',placeItems:'center',padding:20}}><div onClick={e=>e.stopPropagation()} className="card" style={{maxWidth:'90vw',maxHeight:'90vh'}}><img src={light.public_url} alt={light.caption||light.file_name} style={{maxWidth:'85vw',maxHeight:'75vh',objectFit:'contain'}}/><div style={{marginTop:8}}><b>{light.caption||light.file_name}</b><div className="small muted">Progress evidence · {light.taken_at||'Date not provided'}</div></div><button className="btn" style={{marginTop:10}} onClick={()=>setLight(null)}>Close</button></div></div>}
 </>;
}
